### ISSUE TITLE
I HATE LOCAL MEMORY PLEASE DESTROY IT

### ISSUE THREAD

**Issue by modrake** [beandrake/sandbox64#4]
I am concerned that the helloworld program isn't adequately recursive. How can I run this on modern cloud infra if it doesn't recurse? Please implement with a recursion flag.

**Comment by beandrake** [comment]
This actually echos feedback from our recent focus tests: users were satisfied with all aspects of the product but when they heard it wasn't recursive, the response was nearly unanimous that "I don't know what that is but it sounds cool so I want it."  I'll get to work on this right away.

**Comment by beandrake** [comment]
Since the request for this feature was nearly unanimous, we opted to implement it as the default rather than a flag.  Implemented with https://github.com/beandrake/sandbox64/pull/5
